# Config file for automatic testing at travis-ci.org
language: python
python:
  - 3.6
services:
  - docker
install:
  - docker build -t dcs .
  - docker run -d -p 8000:5000 --name dcs dcs

script:
  - docker ps | grep -q dcs
