"""empty message

Revision ID: 00693b3ccd13
Revises: dacdddd0a746
Create Date: 2019-01-31 11:30:01.868992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00693b3ccd13'
down_revision = 'dacdddd0a746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('web_temp_control', sa.Column('port', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('web_temp_control', 'port')
    # ### end Alembic commands ###
