"""empty message

Revision ID: 22c65b97123e
Revises: 51191b95e41a
Create Date: 2018-12-17 13:15:27.589850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22c65b97123e'
down_revision = '51191b95e41a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arduino_serial', sa.Column('baud_rate', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arduino_serial', 'baud_rate')
    # ### end Alembic commands ###
