"""empty message

Revision ID: 2e4e37ce0e31
Revises: 00693b3ccd13
Create Date: 2019-03-02 22:36:26.769446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e4e37ce0e31'
down_revision = '00693b3ccd13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_control', sa.Column('thread_str', sa.String(length=120), nullable=True))
    op.add_column('web_temp_control', sa.Column('thread_str', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('web_temp_control', 'thread_str')
    op.drop_column('temp_control', 'thread_str')
    # ### end Alembic commands ###
