"""Add the camera

Revision ID: 302cc032b715
Revises: 
Create Date: 2018-06-28 13:34:05.683213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302cc032b715'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('switch', sa.Boolean(), nullable=True),
    sa.Column('unit_of_work', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('ard_str', sa.String(length=120), nullable=True),
    sa.Column('folder', sa.String(length=240), nullable=True),
    sa.Column('xMin', sa.Integer(), nullable=True),
    sa.Column('xMax', sa.Integer(), nullable=True),
    sa.Column('yMin', sa.Integer(), nullable=True),
    sa.Column('yMax', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('camera')
    # ### end Alembic commands ###
