"""empty message

Revision ID: 36b8d31633f2
Revises: 71e10b28dc63
Create Date: 2018-06-29 09:00:02.267844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36b8d31633f2'
down_revision = '71e10b28dc63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_control', sa.Column('setpoint', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temp_control', 'setpoint')
    # ### end Alembic commands ###
