"""empty message

Revision ID: 3ced9dd1c99f
Revises: 302cc032b715
Create Date: 2018-06-29 07:14:42.501040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ced9dd1c99f'
down_revision = '302cc032b715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camera', sa.Column('thread_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'camera', ['thread_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'camera', type_='unique')
    op.drop_column('camera', 'thread_id')
    # ### end Alembic commands ###
