"""empty message

Revision ID: 51191b95e41a
Revises: 36b8d31633f2
Create Date: 2018-07-10 11:03:48.093910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51191b95e41a'
down_revision = '36b8d31633f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arduino_serial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.Column('switch', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('ard_str', sa.String(length=120), nullable=True),
    sa.Column('serial_port', sa.String(length=64), nullable=True),
    sa.Column('sleeptime', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arduino_serial')
    # ### end Alembic commands ###
