"""arduino readings

Revision ID: 59a7192d64c5
Revises: 65a386707680
Create Date: 2019-12-12 20:34:24.767101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59a7192d64c5'
down_revision = '65a386707680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('web_temp_control', sa.Column('error', sa.Float(), nullable=True))
    op.add_column('web_temp_control', sa.Column('output', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('web_temp_control', 'output')
    op.drop_column('web_temp_control', 'error')
    # ### end Alembic commands ###
