"""timestamp

Revision ID: 65a386707680
Revises: b42dbbba46e8
Create Date: 2019-12-12 20:21:33.833658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65a386707680'
down_revision = 'b42dbbba46e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('web_temp_control', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('web_temp_control', 'timestamp')
    # ### end Alembic commands ###
