"""empty message

Revision ID: 6e5ba1462581
Revises: 
Create Date: 2018-06-29 08:46:25.585684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e5ba1462581'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.Column('switch', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('ard_str', sa.String(length=120), nullable=True),
    sa.Column('folder', sa.String(length=240), nullable=True),
    sa.Column('xMin', sa.Integer(), nullable=True),
    sa.Column('xMax', sa.Integer(), nullable=True),
    sa.Column('yMin', sa.Integer(), nullable=True),
    sa.Column('yMax', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id')
    )
    op.create_table('temp_control',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.Column('switch', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('ard_str', sa.String(length=120), nullable=True),
    sa.Column('gain', sa.Float(), nullable=True),
    sa.Column('integral', sa.Float(), nullable=True),
    sa.Column('diff', sa.Float(), nullable=True),
    sa.Column('sleeptime', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temp_control')
    op.drop_table('camera')
    # ### end Alembic commands ###
