"""empty message

Revision ID: 71e10b28dc63
Revises: 6e5ba1462581
Create Date: 2018-06-29 08:53:02.267496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71e10b28dc63'
down_revision = '6e5ba1462581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_control', sa.Column('serial_port', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temp_control', 'serial_port')
    # ### end Alembic commands ###
