"""device owners

Revision ID: 75bd6f3444a8
Revises: c2c21bc80130
Create Date: 2019-03-27 08:13:17.094481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75bd6f3444a8'
down_revision = 'c2c21bc80130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('web_temp_control', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'web_temp_control', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'web_temp_control', type_='foreignkey')
    op.drop_column('web_temp_control', 'user_id')
    # ### end Alembic commands ###
