"""empty message

Revision ID: dacdddd0a746
Revises: 22c65b97123e
Create Date: 2019-01-30 17:40:52.873269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dacdddd0a746'
down_revision = '22c65b97123e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_temp_control',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.Column('switch', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('ard_str', sa.String(length=120), nullable=True),
    sa.Column('ip_adress', sa.String(length=64), nullable=True),
    sa.Column('setpoint', sa.Float(), nullable=True),
    sa.Column('gain', sa.Float(), nullable=True),
    sa.Column('integral', sa.Float(), nullable=True),
    sa.Column('diff', sa.Float(), nullable=True),
    sa.Column('sleeptime', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('web_temp_control')
    # ### end Alembic commands ###
